<a href="https://colab.research.google.com/github/chingyaousf/Intern-project/blob/main/DeepDEP_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Importing Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


In [3]:
# Loading the Dataset
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv")
data

DepMap_ID  A1BG (1) Exp  A1CF (29974) Exp  A2M (2) Exp  \
0     ACH-000001      3.116032          0.056584     0.226509   
1     ACH-000004      4.178715          0.000000     0.214125   
2     ACH-000005      4.003602          0.014355     0.137504   
3     ACH-000007      0.137504          1.405992     0.201634   
4     ACH-000009      1.464668          3.586164     0.250962   
...          ...           ...               ...          ...   
1000  ACH-002785      1.967169          0.000000     2.198494   
1001  ACH-002800      3.847997          0.000000     5.899901   
1002  ACH-002834      1.819668          0.014355     0.014355   
1003  ACH-002847      2.990955          0.000000     7.608440   
1004  ACH-002926      3.189034          0.000000     9.335390   

      A2ML1 (144568) Exp  A3GALT2 (127550) Exp  A4GALT (53947) Exp  \
0               0.111031              0.000000            1.035624   
1               0.344828              0.070389            0.097611   
2               0.014355              0.000000            0.028569   
3               0.000000              0.000000            0.014355   
4               0.000000              0.042644            4.525443   
...                  ...                   ...                 ...   
1000            0.000000              0.000000            1.490570   
1001            0.321928              0.000000            3.206331   
1002            0.201634              0.000000            2.912650   
1003            0.014355              0.000000            0.584963   
1004            0.014355              0.000000            0.000000   

      A4GNT (51146) Exp  AAAS (8086) Exp  AACS (65985) Exp  ...  \
0              0.176323         5.700440          4.144046  ...   
1              0.000000         6.336819          3.231125  ...   
2              0.000000         6.337176          3.781360  ...   
3              0.000000         5.431289          4.300856  ...   
4              0.000000         5.674122          4.510962  ...   
...                 ...              ...               ...  ...   
1000           0.000000         5.300490          4.314697  ...   
1001           0.000000         5.831877          3.822730  ...   
1002           0.028569         5.646451          4.547820  ...   
1003           0.000000         5.104337          4.228819  ...   
1004           0.014355         5.204376          4.405992  ...   

      ZYG11A (440590) Exp  ZYG11B (79699) Exp  ZYX (7791) Exp  \
0                3.282440            2.797013        6.821455   
1                0.014355            2.032101        7.002252   
2                0.014355            2.761285        6.826421   
3                0.014355            1.989139        6.332708   
4                1.356144            2.956057        7.853185   
...                   ...                 ...             ...   
1000             0.014355            4.173127        6.560256   
1001             0.622930            3.084064        6.596935   
1002             1.400538            2.568032        6.953498   
1003             1.480265            2.748461        7.432041   
1004             0.014355            2.776104        5.182295   

      ZZEF1 (23140) Exp  ZZZ3 (26009) Exp  EIF2AK3 (9451) Dep  MYC (4609) Dep  \
0              3.010780          4.381975            0.018546        0.807414   
1              3.444932          4.910733            0.044907        0.999985   
2              3.524816          5.592457            0.009301        1.000000   
3              3.673556          3.469886            0.058868        0.999620   
4              3.442280          3.351911            0.040590        0.979828   
...                 ...               ...                 ...             ...   
1000           2.969012          5.276869            0.038095        0.701928   
1001           3.177918          4.847997            0.177952        0.462993   
1002           3.087463          4.226509            0.002074        0

In [4]:
from numpy import true_divide
# Cleaning Column Names
clean_column_names = {}
for column in data.columns:
    clean_column_names[column] = column.strip().replace(' ', '_').replace('(', '').replace(')', '')

data.rename(columns=clean_column_names, inplace=True)

data

DepMap_ID  A1BG_1_Exp  A1CF_29974_Exp  A2M_2_Exp  A2ML1_144568_Exp  \
0     ACH-000001    3.116032        0.056584   0.226509          0.111031   
1     ACH-000004    4.178715        0.000000   0.214125          0.344828   
2     ACH-000005    4.003602        0.014355   0.137504          0.014355   
3     ACH-000007    0.137504        1.405992   0.201634          0.000000   
4     ACH-000009    1.464668        3.586164   0.250962          0.000000   
...          ...         ...             ...        ...               ...   
1000  ACH-002785    1.967169        0.000000   2.198494          0.000000   
1001  ACH-002800    3.847997        0.000000   5.899901          0.321928   
1002  ACH-002834    1.819668        0.014355   0.014355          0.201634   
1003  ACH-002847    2.990955        0.000000   7.608440          0.014355   
1004  ACH-002926    3.189034        0.000000   9.335390          0.014355   

      A3GALT2_127550_Exp  A4GALT_53947_Exp  A4GNT_51146_Exp  AAAS_8086_Exp  \
0               0.000000          1.035624         0.176323       5.700440   
1               0.070389          0.097611         0.000000       6.336819   
2               0.000000          0.028569         0.000000       6.337176   
3               0.000000          0.014355         0.000000       5.431289   
4               0.042644          4.525443         0.000000       5.674122   
...                  ...               ...              ...            ...   
1000            0.000000          1.490570         0.000000       5.300490   
1001            0.000000          3.206331         0.000000       5.831877   
1002            0.000000          2.912650         0.028569       5.646451   
1003            0.000000          0.584963         0.000000       5.104337   
1004            0.000000          0.000000         0.014355       5.204376   

      AACS_65985_Exp  ...  ZYG11A_440590_Exp  ZYG11B_79699_Exp  ZYX_7791_Exp  \
0           4.144046  ...           3.282440          2.797013      6.821455   
1           3.231125  ...           0.014355          2.032101      7.002252   
2           3.781360  ...           0.014355          2.761285      6.826421   
3           4.300856  ...           0.014355          1.989139      6.332708   
4           4.510962  ...           1.356144          2.956057      7.853185   
...              ...  ...                ...               ...           ...   
1000        4.314697  ...           0.014355          4.173127      6.560256   
1001        3.822730  ...           0.622930          3.084064      6.596935   
1002        4.547820  ...           1.400538          2.568032      6.953498   
1003        4.228819  ...           1.480265          2.748461      7.432041   
1004        4.405992  ...           0.014355          2.776104      5.182295   

      ZZEF1_23140_Exp  ZZZ3_26009_Exp  EIF2AK3_9451_Dep  MYC_4609_Dep  \
0            3.010780        4.381975          0.018546      0.807414   
1            3.444932        4.910733          0.044907      0.999985   
2            3.524816        5.592457          0.009301      1.000000   
3            3.673556        3.469886          0.058868      0.999620   
4            3.442280        3.351911          0.040590      0.979828   
...               ...             ...               ...           ...   
1000         2.969012        5.276869          0.038095      0.701928   
1001         3.177918        4.847997          0.177952      0.462993   
1002         3.087463        4.226509          0.002074      0.911326   
1003         2.903038        4.660495          0.161273      0.704900   
1004         2.956057        3.785551          0.017135      0.963046   

      NQO1_1728_Dep  SF3B1_23451_Dep  SQSTM1_8878_Dep  
0          0.076613         1.000000         0.020657  
1          0.061617         1.000000         0.049385  
2          0.049535         0.994004         0.015969  
3          0.036902         0.999886         0.041706  
4          0.006602        

In [5]:
# Splitting the Dataset
# features = data[['A1BG_1_Exp', 'A1CF_29974_Exp', 'A2M_2_Exp', 'A2ML1_144568_Exp', 'A3GALT2_127550_Exp', 'A4GALT_53947_Exp', 'A4GNT_51146_Exp', 'AAAS_8086_Exp', 'AACS_65985_Exp', 'AADAC_13_Exp']]
# targets = data[['EIF2AK3_9451_Dep', 'MYC_4609_Dep']]


In [6]:
# Exclude 'DepMap_ID' column
data_without_id = data.drop(columns=['DepMap_ID'])

# Extracting Features and Targets
features = data_without_id.drop(columns=[col for col in data_without_id.columns if 'Dep' in col])
targets = data_without_id[[col for col in data_without_id.columns if 'Dep' in col]]

In [8]:
# Extracting Features and Targets
# features = data.drop(columns=['DepMap_ID', 'EIF2AK3_9451_Dep', 'MYC_4609_Dep'])
# targets = data[['EIF2AK3_9451_Dep', 'MYC_4609_Dep']]


In [9]:
# Splitting the Data into Train and Test Sets
X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)


In [10]:
# Scale the features (optional but recommended for neural networks)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
# Create and train the KNN regressor
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train_scaled, y_train)


KNeighborsRegressor()

In [12]:
# Make predictions
y_pred = knn.predict(X_test_scaled)


In [13]:
# Printing Predicted Values
print('Predicted Values:', y_pred)


Predicted Values: [[0.03888122 0.92114662 0.18681475 0.99980324 0.08799738]
 [0.04827021 0.96798686 0.15592661 0.99218619 0.09842274]
 [0.04710013 0.97698989 0.05714121 0.99705625 0.02696166]
 ...
 [0.04415839 0.98936179 0.07272144 0.96895582 0.03276118]
 [0.03813599 0.98991522 0.08984912 0.99758786 0.05901436]
 [0.06286084 0.99265077 0.08066548 0.99368934 0.06160484]]


In [14]:
# Evaluating the Model
# Mean Squared Error. It is a common metric used to measure the average squared difference between the predicted and actual values in regression tasks.
# Lower values of MSE indicate better model performance, as it means the predicted values are closer to the actual values. However, MSE is sensitive to outliers since the squared differences magnify their impact on the overall error.

mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)


Mean Squared Error: 0.010354672199808035


In [15]:
# Mean Absolute Error (MAE) measures the average absolute difference between the predicted and actual values. It gives a straightforward measure of the average prediction error. Lower MAE values indicate better accuracy.

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)


Mean Absolute Error: 0.05144551753048687


In [16]:
# Calculate R-squared (coefficient of determination)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print('Coefficient of Determination (R-squared):', r2)


Coefficient of Determination (R-squared): -0.13671761005737365


In [17]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)

r2 = r2_score(y_test, y_pred)
print('Coefficient of Determination (R-squared):', r2)


Mean Squared Error: 0.010354672199808035
Mean Absolute Error: 0.05144551753048687
Coefficient of Determination (R-squared): -0.13671761005737365


In [18]:
# Retrieve the 'DepMap_ID' column before splitting
depmap_id_column = data['DepMap_ID']

# Create a new DataFrame for the test set with the predicted and actual values
test_data = X_test.copy()

# Add 'DepMap_ID' column to test_data
test_data.insert(0, 'DepMap_ID', depmap_id_column.iloc[X_test.index].values)

for i, col in enumerate(targets.columns):
    pred_col = f'Pred_{col}'
    test_data[pred_col] = y_pred[:, i]
    test_data[col] = y_test.iloc[:, i].values

# Display the updated DataFrame
test_data



DepMap_ID  A1BG_1_Exp  A1CF_29974_Exp  A2M_2_Exp  A2ML1_144568_Exp  \
926  ACH-001858    0.176323        0.056584   0.097611          0.014355   
630  ACH-000962    4.410748        0.028569   0.056584          0.000000   
682  ACH-001164    4.262283        0.000000   5.371210          0.000000   
514  ACH-000799    4.440288        0.014355   6.867773          0.014355   
365  ACH-000571    5.489928        0.000000   0.678072          0.000000   
..          ...         ...             ...        ...               ...   
208  ACH-000339    0.111031        0.014355   0.028569          0.000000   
778  ACH-001454    0.400538        0.000000   0.189034          0.163499   
334  ACH-000522    4.157044        0.000000   0.214125          0.000000   
210  ACH-000343    4.189034        0.042644   0.014355          0.367371   
350  ACH-000549    0.056584        0.000000   0.400538          0.111031   

     A3GALT2_127550_Exp  A4GALT_53947_Exp  A4GNT_51146_Exp  AAAS_8086_Exp  \
926            0.000000          3.035624         0.056584       5.299758   
630            0.028569          1.189034         0.014355       5.620000   
682            0.000000          1.765535         0.000000       5.003152   
514            0.163499          0.641546         0.124328       5.484460   
365            0.042644          3.016140         0.214125       5.319040   
..                  ...               ...              ...            ...   
208            0.000000          1.378512         0.028569       5.497612   
778            0.000000          4.678072         0.000000       4.751678   
334            0.000000          2.893362         0.014355       6.321026   
210            0.000000          2.304511         0.097611       5.744699   
350            0.028569          5.224581         0.000000       5.139142   

     AACS_65985_Exp  ...  Pred_EIF2AK3_9451_Dep  EIF2AK3_9451_Dep  \
926        4.263034  ...               0.038881          0.089924   
630        4.238023  ...               0.048270          0.013249   
682        3.489286  ...               0.047100          0.128009   
514        4.268285  ...               0.057795          0.119600   
365        4.609400  ...               0.100156          0.055957   
..              ...  ...                    ...               ...   
208        3.605257  ...               0.038512          0.019725   
778        4.521051  ...               0.078396          0.007032   
334        3.298658  ...               0.044158          0.031388   
210        4.082362  ...               0.038136          0.063896   
350        3.994580  ...               0.062861          0.064660   

     Pred_MYC_4609_Dep  MYC_4609_Dep  Pred_NQO1_1728_Dep  NQO1_1728_Dep  \
926           0.921147      0.986031            0.186815       0.061362   
630           0.967987      0.808635            0.155927       0.424683   
682           0.976990      0.999965            0.057141       0.006208   
514           0.940662      0.973706            0.228258       0.046536   
365           0.952810      0.947456            0.126908       0.135590   
..                 ...           ...                 ...            ...   
208           0.984273      0.981174            0.106256       0.196715   
778           0.985700      0.851388            0.123603       0.046067   
334           0.989362      0.999722            0.072721       0.300746   
210           0.989915      0.971561            0.089849       0.086851   
350           0.992651      0.999956            0.080665       0.055492   

     Pred_SF3B1_23451_Dep  SF3B1_23451_Dep  Pred_SQSTM1_8878_Dep  \
926              0.999803         0.965198              0.087997   
630              0.992186         0.999715              0.098423   
682              0.997056         0.989402              0.026962   
514              0.997888         1.000000              0.153988   
365              0.978819         0.999373              0.105014   
..                    ...     