<a href="https://colab.research.google.com/github/chingyaousf/Intern-project-2023/blob/main/scripts/MLpredictionDep_03_Model_RF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing Libraries
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


In [ ]:
# Loading the Dataset
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv")
# data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_02.csv")
data

DepMap_ID  A1BG (1) Exp  A1CF (29974) Exp  A2M (2) Exp  \
0     ACH-000001      3.116032          0.056584     0.226509   
1     ACH-000004      4.178715          0.000000     0.214125   
2     ACH-000005      4.003602          0.014355     0.137504   
3     ACH-000007      0.137504          1.405992     0.201634   
4     ACH-000009      1.464668          3.586164     0.250962   
...          ...           ...               ...          ...   
1000  ACH-002785      1.967169          0.000000     2.198494   
1001  ACH-002800      3.847997          0.000000     5.899901   
1002  ACH-002834      1.819668          0.014355     0.014355   
1003  ACH-002847      2.990955          0.000000     7.608440   
1004  ACH-002926      3.189034          0.000000     9.335390   

      A2ML1 (144568) Exp  A3GALT2 (127550) Exp  A4GALT (53947) Exp  \
0               0.111031              0.000000            1.035624   
1               0.344828              0.070389            0.097611   
2               0.014355              0.000000            0.028569   
3               0.000000              0.000000            0.014355   
4               0.000000              0.042644            4.525443   
...                  ...                   ...                 ...   
1000            0.000000              0.000000            1.490570   
1001            0.321928              0.000000            3.206331   
1002            0.201634              0.000000            2.912650   
1003            0.014355              0.000000            0.584963   
1004            0.014355              0.000000            0.000000   

      A4GNT (51146) Exp  AAAS (8086) Exp  AACS (65985) Exp  ...  \
0              0.176323         5.700440          4.144046  ...   
1              0.000000         6.336819          3.231125  ...   
2              0.000000         6.337176          3.781360  ...   
3              0.000000         5.431289          4.300856  ...   
4              0.000000         5.674122          4.510962  ...   
...                 ...              ...               ...  ...   
1000           0.000000         5.300490          4.314697  ...   
1001           0.000000         5.831877          3.822730  ...   
1002           0.028569         5.646451          4.547820  ...   
1003           0.000000         5.104337          4.228819  ...   
1004           0.014355         5.204376          4.405992  ...   

      ZYG11A (440590) Exp  ZYG11B (79699) Exp  ZYX (7791) Exp  \
0                3.282440            2.797013        6.821455   
1                0.014355            2.032101        7.002252   
2                0.014355            2.761285        6.826421   
3                0.014355            1.989139        6.332708   
4                1.356144            2.956057        7.853185   
...                   ...                 ...             ...   
1000             0.014355            4.173127        6.560256   
1001             0.622930            3.084064        6.596935   
1002             1.400538            2.568032        6.953498   
1003             1.480265            2.748461        7.432041   
1004             0.014355            2.776104        5.182295   

      ZZEF1 (23140) Exp  ZZZ3 (26009) Exp  EIF2AK3 (9451) Dep  MYC (4609) Dep  \
0              3.010780          4.381975            0.018546        0.807414   
1              3.444932          4.910733            0.044907        0.999985   
2              3.524816          5.592457            0.009301        1.000000   
3              3.673556          3.469886            0.058868        0.999620   
4              3.442280          3.351911            0.040590        0.979828   
...                 ...               ...                 ...             ...   
1000           2.969012          5.276869            0.038095        0.701928   
1001           3.177918          4.847997            0.177952        0.462993   
1002           3.087463          4.226509            0.002074        0

In [ ]:
# Loading the Dataset
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_modified.csv")

data

DepMap_ID  AAK1 (22848) Exp  ABCA4 (24) Exp  ABCB6 (10058) Exp  \
0     ACH-000001          3.078951        2.443607           4.811985   
1     ACH-000004          2.292782        0.713696           4.973152   
2     ACH-000005          2.625270        0.163499           5.231509   
3     ACH-000007          1.970854        0.070389           3.392317   
4     ACH-000009          3.397803        0.070389           5.590662   
...          ...               ...             ...                ...   
1000  ACH-002785          3.819668        0.238787           3.730096   
1001  ACH-002800          4.034744        1.967169           2.805292   
1002  ACH-002834          4.133399        1.786596           3.226509   
1003  ACH-002847          3.396434        0.400538           3.379898   
1004  ACH-002926          3.033863        0.000000           4.672991   

      ABCD3 (5825) Exp  ABI2 (10152) Exp  ABLIM2 (84448) Exp  \
0             4.746313          5.388534            1.510962   
1             4.727920          5.187055            0.000000   
2             5.802452          5.328406            0.028569   
3             4.532940          3.499527            2.386811   
4             5.454834          4.841470            0.084064   
...                ...               ...                 ...   
1000          5.890933          5.172728            0.189034   
1001          5.292414          4.761817            0.731183   
1002          4.999098          4.737146            0.214125   
1003          4.888500          4.164304            0.042644   
1004          4.822730          4.914565            0.000000   

      ACAD8 (27034) Exp  ACAP3 (116983) Exp  ACER3 (55331) Exp  ...  \
0              2.918386            4.514753           5.980025  ...   
1              6.191997            3.166715           3.648465  ...   
2              5.561632            2.464668           4.025029  ...   
3              4.410070            4.799605           2.283922  ...   
4              5.183883            4.221877           3.549669  ...   
...                 ...                 ...                ...  ...   
1000           2.695994            1.895303           2.313246  ...   
1001           4.161081            1.910733           3.206331  ...   
1002           3.351911            2.464668           2.799087  ...   
1003           2.482848            3.649615           6.646451  ...   
1004           3.509696            3.845992           3.496974  ...   

      ZNF862 (643641) Exp  ZNFX1 (57169) Exp  ZRANB2 (9406) Exp  \
0                2.629939           4.003602           6.157044   
1                1.560715           2.904966           7.344917   
2                1.700440           3.166715           7.609179   
3                2.435629           3.051372           5.645010   
4                1.395063           4.263786           5.151372   
...                   ...                ...                ...   
1000             2.773996           4.753284           6.036064   
1001             2.408712           3.614710           5.499846   
1002             0.887525           4.932156           5.254367   
1003             1.925999           3.484138           5.189825   
1004             2.516015           3.512227           5.825531   

      ZYG11B (79699) Exp  ZYX (7791) Exp  EIF2AK3 (9451) Dep  MYC (4609) Dep  \
0               2.797013        6.821455            0.018546        0.807414   
1               2.032101        7.002252            0.044907        0.999985   
2               2.761285        6.826421            0.009301        1.000000   
3               1.989139        6.332708            0.058868        0.999620   
4               2.956057        7.853185            0.040590        0.979828   
...                  ...             ...                 ...             ...   
1000            4.173127        6.560256            0.038095        0.701928   
1001            3.084064        6.596935            0.177952   

In [ ]:
from numpy import true_divide
# Cleaning Column Names
clean_column_names = {}
for column in data.columns:
    clean_column_names[column] = column.strip().replace(' ', '_').replace('(', '').replace(')', '')

data.rename(columns=clean_column_names, inplace=True)

data

DepMap_ID  AAK1_22848_Exp  ABCA4_24_Exp  ABCB6_10058_Exp  \
0     ACH-000001        3.078951      2.443607         4.811985   
1     ACH-000004        2.292782      0.713696         4.973152   
2     ACH-000005        2.625270      0.163499         5.231509   
3     ACH-000007        1.970854      0.070389         3.392317   
4     ACH-000009        3.397803      0.070389         5.590662   
...          ...             ...           ...              ...   
1000  ACH-002785        3.819668      0.238787         3.730096   
1001  ACH-002800        4.034744      1.967169         2.805292   
1002  ACH-002834        4.133399      1.786596         3.226509   
1003  ACH-002847        3.396434      0.400538         3.379898   
1004  ACH-002926        3.033863      0.000000         4.672991   

      ABCD3_5825_Exp  ABI2_10152_Exp  ABLIM2_84448_Exp  ACAD8_27034_Exp  \
0           4.746313        5.388534          1.510962         2.918386   
1           4.727920        5.187055          0.000000         6.191997   
2           5.802452        5.328406          0.028569         5.561632   
3           4.532940        3.499527          2.386811         4.410070   
4           5.454834        4.841470          0.084064         5.183883   
...              ...             ...               ...              ...   
1000        5.890933        5.172728          0.189034         2.695994   
1001        5.292414        4.761817          0.731183         4.161081   
1002        4.999098        4.737146          0.214125         3.351911   
1003        4.888500        4.164304          0.042644         2.482848   
1004        4.822730        4.914565          0.000000         3.509696   

      ACAP3_116983_Exp  ACER3_55331_Exp  ...  ZNF862_643641_Exp  \
0             4.514753         5.980025  ...           2.629939   
1             3.166715         3.648465  ...           1.560715   
2             2.464668         4.025029  ...           1.700440   
3             4.799605         2.283922  ...           2.435629   
4             4.221877         3.549669  ...           1.395063   
...                ...              ...  ...                ...   
1000          1.895303         2.313246  ...           2.773996   
1001          1.910733         3.206331  ...           2.408712   
1002          2.464668         2.799087  ...           0.887525   
1003          3.649615         6.646451  ...           1.925999   
1004          3.845992         3.496974  ...           2.516015   

      ZNFX1_57169_Exp  ZRANB2_9406_Exp  ZYG11B_79699_Exp  ZYX_7791_Exp  \
0            4.003602         6.157044          2.797013      6.821455   
1            2.904966         7.344917          2.032101      7.002252   
2            3.166715         7.609179          2.761285      6.826421   
3            3.051372         5.645010          1.989139      6.332708   
4            4.263786         5.151372          2.956057      7.853185   
...               ...              ...               ...           ...   
1000         4.753284         6.036064          4.173127      6.560256   
1001         3.614710         5.499846          3.084064      6.596935   
1002         4.932156         5.254367          2.568032      6.953498   
1003         3.484138         5.189825          2.748461      7.432041   
1004         3.512227         5.825531          2.776104      5.182295   

      EIF2AK3_9451_Dep  MYC_4609_Dep  NQO1_1728_Dep  SF3B1_23451_Dep  \
0             0.018546      0.807414       0.076613         1.000000   
1             0.044907      0.999985       0.061617         1.000000   
2             0.009301      1.000000       0.049535         0.994004   
3             0.058868      0.999620       0.036902         0.999886   
4             0.040590      0.979828       0.006602         0.973598   
...                ...           ...            ...              ...   
1000          0.038095      0.701928       0.161286         1.000000   
1001          0.177952      0.4

In [ ]:
# Exclude 'DepMap_ID' column
data_without_id = data.drop(columns=['DepMap_ID'])

# Extracting Features and Targets
features = data_without_id.drop(columns=[col for col in data_without_id.columns if 'Dep' in col])
targets = data_without_id[[col for col in data_without_id.columns if 'Dep' in col]]

features

In [ ]:
# Exclude 'DepMap_ID' column
data_without_id = data.drop(columns=['DepMap_ID'])

# Extracting Features and Targets
features = data_without_id.drop(columns=[col for col in data_without_id.columns if 'Dep' in col])
#targets = data_without_id[[col for col in data_without_id.columns if 'Dep' in col]]
targets = data_without_id[["MYC_4609_Dep"]]

In [ ]:
# Splitting the Data into Train and Test Sets
X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)


In [ ]:
# Creating and Training the Random Forest Regressor
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)


RandomForestRegressor(random_state=42)

In [ ]:
# Making Predictions
y_pred = rf.predict(X_test)


In [ ]:
# Printing Predicted Values
print('Predicted Values:', y_pred)


Predicted Values: [[0.05124441 0.96992762 0.09430055 0.99131036 0.07319323]
 [0.05946172 0.9833637  0.09706235 0.99426044 0.05848171]
 [0.08174098 0.98215347 0.0693352  0.99019277 0.05993472]
 ...
 [0.05895578 0.96910185 0.08663162 0.99177932 0.06394183]
 [0.07082637 0.92126339 0.10197466 0.98530371 0.05975604]
 [0.06358054 0.96769988 0.09127848 0.98993161 0.05685971]]


In [ ]:
# Evaluating the Model
# Mean Squared Error. It is a common metric used to measure the average squared difference between the predicted and actual values in regression tasks.
# Lower values of MSE indicate better model performance, as it means the predicted values are closer to the actual values. However, MSE is sensitive to outliers since the squared differences magnify their impact on the overall error.

mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)


Mean Squared Error: 0.007742492746486128


In [ ]:
# Mean Absolute Error (MAE) measures the average absolute difference between the predicted and actual values. It gives a straightforward measure of the average prediction error. Lower MAE values indicate better accuracy.

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)


Mean Absolute Error: 0.0474472916903526


In [ ]:
# R-squared (coefficient of determination) measures the proportion of the variance in the target variable that is explained by the model. It ranges from 0 to 1

r_squared = rf.score(X_test, y_test)
print('R-squared:', r_squared)


R-squared: 0.08684119167732784


In [ ]:
# Evaluating the Model

from sklearn.metrics import mean_absolute_error

mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)

r_squared = rf.score(X_test, y_test)
print('R-squared:', r_squared)

Mean Squared Error: 0.007742492746486128
Mean Absolute Error: 0.0474472916903526
R-squared: 0.08684119167732784


In [ ]:
# Evaluating the Model

from sklearn.metrics import mean_absolute_error

mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)

r_squared = rf.score(X_test, y_test)
print('R-squared:', r_squared)

Mean Squared Error: 0.007742189746968153
Mean Absolute Error: 0.048028355668757336
R-squared: 0.07835222770554473


In [ ]:
# Retrieve the 'DepMap_ID' column before splitting
depmap_id_column = data['DepMap_ID']

# Create a new DataFrame for the test set with the predicted and actual values
test_data = X_test.copy()

# Add 'DepMap_ID' column to test_data
test_data.insert(0, 'DepMap_ID', depmap_id_column.iloc[X_test.index].values)

for i, col in enumerate(targets.columns):
    pred_col = f'Pred_{col}'
    test_data[pred_col] = y_pred[:, i]
    test_data[col] = y_test.iloc[:, i].values

# Save the DataFrame to a CSV file
test_data.to_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/test_data_RF1_01.csv", index=False)

# Display the updated DataFrame
test_data



NameError: ignored

In [ ]:
# Retrieve the 'DepMap_ID' column before splitting
depmap_id_column = data['DepMap_ID']

# Create a new DataFrame for the test set with the predicted and actual values
test_data = X_test.copy()

# Add 'DepMap_ID' column to test_data
test_data.insert(0, 'DepMap_ID', depmap_id_column.iloc[X_test.index].values)

for i, col in enumerate(targets.columns):
    pred_col = f'Pred_{col}'
    test_data[pred_col] = y_pred[:, i]
    test_data[col] = y_test.iloc[:, i].values

# Save the DataFrame to a CSV file
test_data.to_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/test_data_RF2_01.csv", index=False)

# Display the updated DataFrame
test_data


DepMap_ID  AAK1_22848_Exp  ABCA4_24_Exp  ABCB6_10058_Exp  \
926  ACH-001858        2.906891      2.032101         4.060047   
630  ACH-000962        2.438293      0.084064         3.661065   
682  ACH-001164        2.063503      1.226509         3.900142   
514  ACH-000799        3.282440      0.214125         5.572283   
365  ACH-000571        3.517276      1.443607         6.077457   
..          ...             ...           ...              ...   
208  ACH-000339        3.252476      0.344828         4.621173   
778  ACH-001454        2.944858      0.495695         4.793896   
334  ACH-000522        3.329124      0.226509         1.560715   
210  ACH-000343        3.632268      0.014355         2.801159   
350  ACH-000549        3.600508      0.201634         2.432959   

     ABCD3_5825_Exp  ABI2_10152_Exp  ABLIM2_84448_Exp  ACAD8_27034_Exp  \
926        5.081936        4.837943          0.097611         3.869871   
630        4.712596        5.013909          0.713696         4.624101   
682        3.836934        3.865919          1.035624         3.343408   
514        4.468583        5.457463          0.941106         3.953265   
365        5.211791        4.825277          0.250962         4.560715   
..              ...             ...               ...              ...   
208        5.074249        5.397461          0.042644         4.806840   
778        4.095080        3.548437          1.007196         5.174327   
334        4.943453        5.174327          0.097611         4.247928   
210        4.775577        6.491051          0.823749         4.959306   
350        4.226509        4.096768          1.007196         3.970854   

     ACAP3_116983_Exp  ACER3_55331_Exp  ...  Pred_EIF2AK3_9451_Dep  \
926          3.073820         2.750607  ...               0.051244   
630          3.047887         3.231125  ...               0.059462   
682          3.037382         1.922198  ...               0.081741   
514          5.381975         2.545968  ...               0.069693   
365          5.453188         2.889474  ...               0.057725   
..                ...              ...  ...                    ...   
208          5.069960         3.371559  ...               0.048227   
778          2.954196         2.845992  ...               0.064769   
334          3.599318         3.862947  ...               0.058956   
210          5.246028         3.799087  ...               0.070826   
350          5.049631         2.849999  ...               0.063581   

     EIF2AK3_9451_Dep  Pred_MYC_4609_Dep  MYC_4609_Dep  Pred_NQO1_1728_Dep  \
926          0.089924           0.969928      0.986031            0.094301   
630          0.013249           0.983364      0.808635            0.097062   
682          0.128009           0.982153      0.999965            0.069335   
514          0.119600           0.758875      0.973706            0.094607   
365          0.055957           0.866239      0.947456            0.091318   
..                ...                ...           ...                 ...   
208          0.019725           0.982920      0.981174            0.079610   
778          0.007032           0.946034      0.851388            0.092636   
334          0.031388           0.969102      0.999722            0.086632   
210          0.063896           0.921263      0.971561            0.101975   
350          0.064660           0.967700      0.999956            0.091278   

     NQO1_1728_Dep  Pred_SF3B1_23451_Dep  SF3B1_23451_Dep  \
926       0.061362              0.991310         0.965198   
630       0.424683              0.994260         0.999715   
682       0.006208              0.990193         0.989402   
514       0.046536              0.991396         1.000000   
365       0.135590              0.990551         0.999373   
..             ...                   ...              ...   
208       0.196715              0.990378         0.977665   
778       0.046067              0.987873         1.000000 